# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 448b0d4b8e2a582415aa29e11e290cb3e2eb06c52e668de6ff77dbbb3754e47f0bc2dd0b2c1bbb71a5a18edb8bea021b6d3b2ee943f5d6776b06be3caa594efb

test:
  secret_key_base: 3e5eca65d58f38dac715ec0f84d0fb0801f5a20fbe4622e0d6009f5b0a200a2f189ee305b5f62fbbda0490da1fde11f55d28c5e4d5af01d6a5b6e595607d09c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
